### ISSUE TITLE
Segmentation fault on Raspberry Pi

### ISSUE THREAD

**Issue by vk3il** [wb2osz/direwolf#124]
I am trying to use v1.4 compiled from source on the Raspberry Pi under Jessie. I am getting a segmentation fault as follows:

```
(gdb) run -a 180 -t 0 -c /tmp/direwolf.conf -l /var/log/direwolf -d ii
Starting program: /usr/local/bin/direwolf -a 180 -t 0 -c /tmp/direwolf.conf -l /var/log/direwolf -d ii
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
Dire Wolf version 1.4
Includes optional support for:  gpsd

Reading config file /tmp/direwolf.conf
Audio device for both receive and transmit: plughw:CARD=udrc,DEV=0  (channels 0 & 1)
Channel 0: 1200 baud, AFSK 1200 & 2200 Hz, E+, 48000 sample rate / 3.
Channel 1: 300 baud, AFSK 1600 & 1800 Hz, D, 48000 sample rate / 3.
[New Thread 0x76b16450 (LWP 20288)]
[New Thread 0x76316450 (LWP 20289)]
igate_init ( aunz.aprs2.net, 14580, VK3IL, 12345, (null) )
[New Thread 0x75b16450 (LWP 20290)]
DEBUG: igate connect_thread start, port = 14580 = '14580'
[New Thread 0x75316450 (LWP 20291)]
igate_recv_thread ( socket = -1 )
[New Thread 0x74b16450 (LWP 20292)]
Ready to accept AGW client application 0 on port 8000 ...
[New Thread 0x74316450 (LWP 20293)]
[New Thread 0x73b16450 (LWP 20294)]
[New Thread 0x73316450 (LWP 20295)]
[New Thread 0x72b16450 (LWP 20296)]
Ready to accept KISS client application on port 8001 ...
[New Thread 0x72316450 (LWP 20297)]
Use -p command line option to enable KISS pseudo terminal.
[New Thread 0x71afa450 (LWP 20298)]
[New Thread 0x712fa450 (LWP 20299)]
[New Thread 0x70afa450 (LWP 20300)]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x75b16450 (LWP 20290)]
__GI_strcmp (p1=<optimized out>, p2=0x2500c8 "") at strcmp.c:37
37	strcmp.c: No such file or directory.
(gdb) bt
#0  __GI_strcmp (p1=<optimized out>, p2=0x2500c8 "") at strcmp.c:37
#1  0x76d9a7d0 in nss_new_service (name=0x2500c8 "", database=<optimized out>) at nsswitch.c:813
#2  nss_load_library (ni=0x2500a8) at nsswitch.c:337
#3  0x76d9b154 in __GI___nss_lookup_function (ni=ni@entry=0x2500a8, 
    fct_name=fct_name@entry=0x76dca7a4 "gethostbyname4_r") at nsswitch.c:466
#4  0x76d63060 in gaih_inet (name=<optimized out>, name@entry=0x7effe3a0 "aunz.aprs2.net", 
    service=<optimized out>, req=req@entry=0x75b15c18, pai=pai@entry=0x75b15b28, naddrs=naddrs@entry=0x75b15b34)
    at ../sysdeps/posix/getaddrinfo.c:861
#5  0x76d64520 in __GI_getaddrinfo (name=0x7effe3a0 "aunz.aprs2.net", service=0x75b15c0c "14580", 
    service@entry=0x75b15c04 "", hints=0x75b15c18, hints@entry=0x75b15c10, pai=0x75b15c08, pai@entry=0x75b15c00)
    at ../sysdeps/posix/getaddrinfo.c:2426
#6  0x00050db4 in connnect_thread (arg=<optimized out>) at igate.c:647
#7  0x76f09e90 in start_thread (arg=0x75b16450) at pthread_create.c:311
#8  0x76d79598 in ?? () at ../ports/sysdeps/unix/sysv/linux/arm/nptl/../clone.S:92
   from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) 
```
**Here's the config file used:**
```


ADEVICE plughw:CARD=udrc,DEV=0

ACHANNELS 2
ARATE 48000

CHANNEL 0

MYCALL VK3IL-12 # Tracker

MODEM 1200

PTT GPIO 12


CHANNEL 1

MYCALL VK3IL-12 # Tracker

MODEM 300

PTT GPIO 23

AGWPORT 8000
KISSPORT 8001


GPSD localhost

SMARTBEACONING 35 2:00 5 15:00 0:15 30 255

TBEACON SENDTO=0 SYMBOL=\> FREQ=146.500 VIA=WIDE1-1,WIDE2-1
TBEACON SENDTO=IG SYMBOL=\> FREQ=146.500


IGSERVER aunz.aprs2.net

IGLOGIN VK3IL 12345



```
Any help or pointers greatly appreciated. Note that I ran the gdb session as root in case there were any permission errors.

Thanks

David VK3IL

**Comment by wb2osz** [comment]
This was more than 2 years ago.  Please reopen if still an issue with current version.  Thanks.
